
/*******************************************************************************
THIS DOCUMENT EXPORTS A LATEX FILE WHICH CANNOT BE RUN. THE FILE CAN BE IMPORTED
IN A LATEX DPCUMENT BUT IT CANNOT BE RUN ON ITS OWN BECAUSE THE DOCUMENT CLASS 
AND THE USED PACKAGES AS WELL AS THE BEGINNING AND THE ENDING OF THE DOCUMENT 
IS NOT SPECIFIED. TO RUN THE TEX FILE GENERATED BY THIS DOFILE, YOU SHOULD 
ADD THE FIRST FOUR COMMANDS AT THE BEGINNING OF THE LATEX FILE AND THE END 
COMMAND AT THE END OF THE DOCUMENT. 


\documentclass{article}
\usepackage{graphicx}
\usepackage{hyperref}
\begin{document}

---

\end{document}
*******************************************************************************/




cd "/Users/haghish/Desktop"
sysuse auto, clear
hist price
graph export graph.png, width(400) replace


qui log using markdown_syntax, replace

/* 





This dofile shows the basic markdown syntax. I recommend not using hashtags for
styling the heading 1 and heading 2, because hashtags makes them less 
distinguishable. 



This is heading 1
=================

This is heading 2
-----------------

###This is heading 3

####This is heading 4

#####This is heading 5

######This is heading 6

This is a text paragraph and its content can be *italic* or **bold**. 
as long as you move on to the next lines without adding 2 or more spaces to the 
end of each line, Markdown will be interpreted as one paragraph and the lines  
appear continuous in your document.


Bold and Italic text
--------------------

to begin a new paragraph, leave an empty line between your text. Also remember  
that you can use underscore to make your text _italic_, __bold__, or even
___italic & bold___. 


Adding a link & graph
---------------------

The syntax for creating a link or inserting a graph using Markdown is fairly 
similar because in a sense, you link the graph to the document. **note that 
while exporting the graph, I resized the graph. This is recommended because 
Markdown inserts the graph in its full size and you cannot resize it. 
Alternatively, you can insert the graph using HTML img tag. 

[link name](http://www.haghish.com/stata "Optional Title")

![This graph shows the histogram of the price variable](graph.png)


Adding bullet list
------------------

- item 1
- item 2
- item 3


*/

qui log c

markdoc markdown_syntax, replace export(tex)
